<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AnimeSeeder extends Seeder
{
    public function run()
    {
        // Assuming categories are already seeded, get category IDs
        $categoryIds = DB::table('categories')->pluck('id', 'name');

        $animes = [
            [
                'title' => 'Attack on Titan',
                'native_title' => '進撃の巨人',
                'description' => 'Humans fight against gigantic humanoid Titans.',
                'user_rating' => 9.0,
                'release_date' => '2013-04-07',
                'duration' => 24,
                'director' => 'Tetsurō Araki',
                'studio' => 'Wit Studio',
                'favorite_count' => 5000,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/aot.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Your Name',
                'native_title' => '君の名は。',
                'description' => 'A body-swapping romance drama.',
                'user_rating' => 9.2,
                'release_date' => '2016-08-26',
                'duration' => 106,
                'director' => 'Makoto Shinkai',
                'studio' => 'CoMix Wave Films',
                'favorite_count' => 8000,
                'category_id' => $categoryIds['Movie'],
                'imageUrl' => 'https://example.com/images/yourname.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Add 8 more anime entries similarly:
            [
                'title' => 'Fullmetal Alchemist: Brotherhood',
                'native_title' => '鋼の錬金術師 FULLMETAL ALCHEMIST',
                'description' => 'Two brothers search for the Philosopher\'s Stone.',
                'user_rating' => 9.1,
                'release_date' => '2009-04-05',
                'duration' => 24,
                'director' => 'Yasuhiro Irie',
                'studio' => 'Bones',
                'favorite_count' => 7000,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/fma.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Demon Slayer',
                'native_title' => '鬼滅の刃',
                'description' => 'A boy becomes a demon slayer to save his sister.',
                'user_rating' => 8.9,
                'release_date' => '2019-04-06',
                'duration' => 24,
                'director' => 'Haruo Sotozaki',
                'studio' => 'ufotable',
                'favorite_count' => 6000,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/demonslayer.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'One Punch Man',
                'native_title' => 'ワンパンマン',
                'description' => 'A superhero who defeats enemies with one punch.',
                'user_rating' => 8.7,
                'release_date' => '2015-10-05',
                'duration' => 24,
                'director' => 'Shingo Natsume',
                'studio' => 'Madhouse',
                'favorite_count' => 5500,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/opm.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Naruto',
                'native_title' => 'ナルト',
                'description' => 'A young ninja seeks recognition and dreams to become Hokage.',
                'user_rating' => 8.3,
                'release_date' => '2002-10-03',
                'duration' => 23,
                'director' => 'Hayato Date',
                'studio' => 'Pierrot',
                'favorite_count' => 9000,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/naruto.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Spirited Away',
                'native_title' => '千と千尋の神隠し',
                'description' => 'A girl enters a mysterious spirit world.',
                'user_rating' => 9.3,
                'release_date' => '2001-07-20',
                'duration' => 125,
                'director' => 'Hayao Miyazaki',
                'studio' => 'Studio Ghibli',
                'favorite_count' => 8500,
                'category_id' => $categoryIds['Movie'],
                'imageUrl' => 'https://example.com/images/spiritedaway.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Death Note',
                'native_title' => 'デスノート',
                'description' => 'A notebook allows killing anyone whose name is written in it.',
                'user_rating' => 9.0,
                'release_date' => '2006-10-04',
                'duration' => 37,
                'director' => 'Tetsurō Araki',
                'studio' => 'Madhouse',
                'favorite_count' => 7800,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/deathnote.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'My Hero Academia',
                'native_title' => '僕のヒーローアカデミア',
                'description' => 'A boy dreams of becoming a hero in a superpowered world.',
                'user_rating' => 8.4,
                'release_date' => '2016-04-03',
                'duration' => 24,
                'director' => 'Kenji Nagasaki',
                'studio' => 'Bones',
                'favorite_count' => 6400,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/mha.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Tokyo Ghoul',
                'native_title' => '東京喰種トーキョーグール',
                'description' => 'A college student becomes a half-ghoul after an attack.',
                'user_rating' => 7.9,
                'release_date' => '2014-07-04',
                'duration' => 24,
                'director' => 'Shūhei Morita',
                'studio' => 'Pierrot',
                'favorite_count' => 4800,
                'category_id' => $categoryIds['TV'],
                'imageUrl' => 'https://example.com/images/tokyoghoul.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('animes')->insert($animes);
    }
}
